#!/bin/sh
SANDBOX_TRUSTED_MUSL_HOME=$SANDBOX_HOME/x86_64-linux-musl-native-trusted
PREFIX="${PREFIX:-${SANDBOX_TRUSTED_MUSL_HOME}}"
LIBCXX="${LIBCXX:-${SANDBOX_TRUSTED_MUSL_HOME}}"
CFLAGS="-Xclang -disable-O0-optnone -gdwarf-3 -fcf-protection $CFLAGS" \
LLVM_HOME=$SANDBOX_HOME/llvm-install \
CLANG=$LLVM_HOME/bin/clang \
LLD=$LLVM_HOME/bin/ld.lld \
CC=$CLANG \
LD=$LLD \
AR=$LLVM_HOME/bin/llvm-ar \
RANLIB=$LLVM_HOME/bin/llvm-ranlib \
CLANGXX=$LLVM_HOME/bin/clang++ \
LLVM_LINK=$LLVM_HOME/bin/llvm-link \
LLVM_OBJCOPY=$LLVM_HOME/bin/llvm-objcopy \
LLVM_AR=$LLVM_HOME/bin/llvm-ar \
LLVM_RANLIB=$LLVM_HOME/bin/llvm-ranlib \
LLVM_CONFIG=$LLVM_HOME/bin/llvm-config \
ALTBUILD="${ALTBUILD:-clang}" \
./configure --prefix=$PREFIX --syslibdir=$PREFIX/lib --libcxxdir=$LIBCXX"$@"

