#!/bin/bash

# LLVM_HOME must be passed as an env var

if [[ -z "${LLVM_HOME}" ]]; then
  echo "LLVM env var is undefined"
  exit -1
fi

readonly SELF_DIR=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

CFLAGS="-sandbox -gdwarf-3 $CFLAGS" \
CLANG_WRAPPER_FLAGS=-sandbox \
CLANG=$LLVM_HOME/bin/clang \
LLD=$LLVM_HOME/bin/ld.lld \
CC=$CLANG \
LD=$LLD \
AR=ar \
RANLIB=ranlib \
CLANGXX=$LLVM_HOME/bin/clang++ \
$SELF_DIR/configure --enable-debug --enable-wrapper=clang --target=x86_64 --libcxxdir=$LIBCXX "$@"

